### PR TITLE
Add flags option to request JSON

### PR DESCRIPTION
**Pull request by mmazour**
### Description

Adds a `flags` parameter to the CLSI request JSON, appearing under the `compile.options` key (alongside such stalwarts as `compiler`, `timeout`, etc.).

This is primarily to support `-file-line-error` as an option, but could have other uses as well.

~~`flags` should be a string, or absent. If supplied, it is split on spaces and the resulting arguments are added to the base latexmk command.~~ `flags` should be an array of strings, or absent. If supplied, the listed arguments are added to the base latexmk command.

#### Screenshots

None.

#### Related Issues / PRs

https://github.com/overleaf/write_latex/pull/5201: CLSI-conversions require Overleaf's LaTeX log parser, which in turn expects logs built with `-file-line-error`. 

### Review

This is fairly straightforward. `RequestParser` captures the `flags` option if present, and stores it alongside the other compilation options. These are eventually passed to `LatexRunner`, which adds the flags to the command returned by `_latexmkBaseCommand` if the flags are present. 

#### Potential Impact

- Touches the core CLSI compilation chain — IMO not in a dangerous way, but you be the judge.

- Allows callers of the CLSI to inject arbitrary strings into the `latexmk` command line. This is nice and general, but it could also be viewed as risky.

#### Manual Testing Performed

None yet. I will test end-to-end in dev before merging.

#### Accessibility

No impact.

### Deployment

Normal.

#### Deployment Checklist

- [ ] Test a regular compile with errors: error lines should begin `! LaTeX Error:` without a filename and line number.
- [ ] Test a compile under https://github.com/overleaf/write_latex/pull/5201 with the project given in https://github.com/overleaf/write_latex/pull/5201#issuecomment-489157568: it should detect the error in the log.

### CODE REVIEW

**Comment by jdleesmiller** [comment]
Seems reasonable to me, but I guess it could be simplified slightly if we passed `flags` as an array? That would avoid the need for the split and any problems that might crop up with escaping spaces.

**Comment by henryoswald** [comment]
An array would be cleaner now you point it out.

**Comment by mmazour** [comment]
It's an array now. Another look, @henryoswald?

**Comment by henryoswald** [comment]
LGTM

**Comment by mmazour** [comment]
Thanks, Henry.

Per https://github.com/overleaf/write_latex/pull/5201#issuecomment-492641607 I've now tested the intended use case (conversions and their log parsing) end to end and determined it works and is fit for purpose.

I'm holding off merging it until I've tried out your comment https://github.com/overleaf/dev-environment/pull/210#issuecomment-492620486 — if that approach does work would you want me to add that env change to this PR, @henryoswald ?

**Comment by henryoswald** [comment]
Great. The change I suggested would only go into the dev env not here so it would be a separate PR.

**Pull request merged**
